In [24]:
import pokerkit as pk

In [87]:
big_blind = 100
small_blind = 0.5*big_blind
blinds = [small_blind, big_blind]
ante = 0.1*big_blind
min_bet = 0.5*big_blind
starting_stack = 100*big_blind
player_count = 5
board_idx = 0 # only one board
hand_type_idx = 0 # corresponds to pk.hand_types.StandHighHand, which is the hand type for NLTH

game = pk.NoLimitTexasHoldem(
    # Automations - everything is automatic except for player actions
    (
        pk.Automation.ANTE_POSTING,
        pk.Automation.BET_COLLECTION,
        pk.Automation.BLIND_OR_STRADDLE_POSTING,
        pk.Automation.CARD_BURNING,
        pk.Automation.HOLE_DEALING,
        pk.Automation.BOARD_DEALING,
        pk.Automation.HOLE_CARDS_SHOWING_OR_MUCKING,
        pk.Automation.HAND_KILLING,
        pk.Automation.CHIPS_PUSHING,
        pk.Automation.CHIPS_PULLING,
    ),
    ante_trimming_status=True, # irrelevant but necessary for the game to be created
    raw_antes=ante,
    raw_blinds_or_straddles=blinds,
    min_bet=min_bet,
)

state = game(raw_starting_stacks=starting_stack, player_count=player_count)
state

State(automations=(<Automation.ANTE_POSTING: 'Ante posting'>, <Automation.BET_COLLECTION: 'Bet collection'>, <Automation.BLIND_OR_STRADDLE_POSTING: 'Blind or straddle posting'>, <Automation.CARD_BURNING: 'Card burning'>, <Automation.HOLE_DEALING: 'Hole dealing'>, <Automation.BOARD_DEALING: 'Board dealing'>, <Automation.HOLE_CARDS_SHOWING_OR_MUCKING: 'Hole cards showing or mucking'>, <Automation.HAND_KILLING: 'Hand killing'>, <Automation.CHIPS_PUSHING: 'Chips pushing'>, <Automation.CHIPS_PULLING: 'Chips pulling'>), deck=<Deck.STANDARD: (2c, 2d, 2h, 2s, 3c, 3d, 3h, 3s, 4c, 4d, 4h, 4s, 5c, 5d, 5h, 5s, 6c, 6d, 6h, 6s, 7c, 7d, 7h, 7s, 8c, 8d, 8h, 8s, 9c, 9d, 9h, 9s, Tc, Td, Th, Ts, Jc, Jd, Jh, Js, Qc, Qd, Qh, Qs, Kc, Kd, Kh, Ks, Ac, Ad, Ah, As)>, hand_types=(<class 'pokerkit.hands.StandardHighHand'>,), streets=(Street(card_burning_status=False, hole_dealing_statuses=(False, False), board_dealing_count=0, draw_status=False, opening=<Opening.POSITION: 'Position'>, min_completion_betting_or_ra

In [88]:
print(f"Pre-flop betting")
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.complete_bet_or_raise_to(150) # UTG (player2)
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() # player3
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() # player4
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() # player0
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() # player1
print(f"Pre-flop betting complete")

Pre-flop betting
Player 2's turn, hand: None, current bets: [50.0, 100, 0, 0, 0], queue: deque([2, 3, 4, 0, 1])
Player 3's turn, hand: None, current bets: [50.0, 100, 150, 0, 0], queue: deque([3, 4, 0, 1])
Player 4's turn, hand: None, current bets: [50.0, 100, 150, 150, 0], queue: deque([4, 0, 1])
Player 0's turn, hand: None, current bets: [50.0, 100, 150, 150, 150], queue: deque([0, 1])
Player 1's turn, hand: None, current bets: [150.0, 100, 150, 150, 150], queue: deque([1])
Pre-flop betting complete


In [89]:
print(f"Post-flop betting, board cards: {state.board_cards}")
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.complete_bet_or_raise_to(150) # UTG (player2)
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() # player3
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() # player4
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() # player0
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() # player1
print("Post flop betting complete")

Post-flop betting, board cards: [[Jh], [8c], [Td]]
Player 0's turn, hand: One pair (6hThJh8cTd), current bets: [0, 0, 0, 0, 0], queue: deque([0, 1, 2, 3, 4])
Player 1's turn, hand: One pair (3sTsJh8cTd), current bets: [150, 0, 0, 0, 0], queue: deque([1, 2, 3, 4])
Player 2's turn, hand: High card (Kh4cJh8cTd), current bets: [150, 150, 0, 0, 0], queue: deque([2, 3, 4])
Player 3's turn, hand: High card (5hQsJh8cTd), current bets: [150, 150, 150, 0, 0], queue: deque([3, 4])
Player 4's turn, hand: High card (9s2dJh8cTd), current bets: [150, 150, 150, 150, 0], queue: deque([4])
Post flop betting complete


In [ ]:
print(f"Fourth street betting, board cards: {state.board_cards}")
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.complete_bet_or_raise_to(150)
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() 
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call()
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() 
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call()
print("Fourth street betting complete")

In [ ]:
print(f"Fifth street betting, board cards: {state.board_cards}")
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.complete_bet_or_raise_to(150)
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() 
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call()
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call() 
print(f"Player {state.actor_index}'s turn, hand: {state.get_hand(state.actor_index, board_idx, hand_type_idx)}, current bets: {state.bets}, queue: {state.actor_indices}")
state.check_or_call()
print("Fourth street betting complete")

In [ ]:
print(f"Final stacks: {state.stacks}")

In [ ]:
filepath =  "models/PyStack/data/TrainSamples/river/root_nodes_npy/boards.0.npy"
import numpy as np
import sys
import os

def visualize_npy(file_path):
    # Load the numpy array
    data = np.load(file_path)
    
    # Print basic information
    print(f"\nFile: {os.path.basename(file_path)}")
    print(f"Shape: {data.shape}")
    print(f"Data type: {data.dtype}")
    print(f"Min value: {np.min(data)}")
    print(f"Max value: {np.max(data)}")
    print(f"Mean value: {np.mean(data)}")
    if file_path == "models/PyStack/data/TrainSamples/river/root_nodes_npy/inputs.0.npy":
        print(f"Last value: {data[0,-1]}")

    # Print first few elements
    print("\nFirst few elements:")
    print(data.flatten()[:10])  # Show first 10 elements
    
    # Print unique values and their counts if the array is small enough
    if data.size < 1000:  # Only for reasonably sized arrays
        unique_vals = np.unique(data, return_counts=True)
        print("\nUnique values and their counts:")
        for val, count in zip(*unique_vals):
            print(f"{val}: {count}")

def main(file_path):
    if not os.path.exists(file_path):
        print(f"File not found: {file_path}")
        return
        
    visualize_npy(file_path)

print(filepath)

for filepath in ["models/PyStack/data/TrainSamples/river/root_nodes_npy/boards.1.npy", "models/PyStack/data/TrainSamples/river/root_nodes_npy/inputs.1.npy", "models/PyStack/data/TrainSamples/river/root_nodes_npy/targets.0.npy"]:
    main(filepath)

models/PyStack/data/TrainSamples/river/root_nodes_npy/boards.0.npy

File: boards.1.npy
Shape: (10, 5)
Data type: uint8
Min value: 3
Max value: 50
Mean value: 26.8

First few elements:
[30 21 47 29 41 26 45 16 27 42]

Unique values and their counts:
3: 1
5: 1
6: 1
8: 1
9: 3
10: 1
11: 1
14: 2
15: 1
16: 1
17: 1
18: 2
19: 2
20: 1
21: 1
22: 1
25: 1
26: 2
27: 2
28: 1
29: 2
30: 3
32: 1
34: 2
37: 1
39: 3
40: 1
41: 1
42: 2
44: 1
45: 1
47: 1
48: 2
49: 1
50: 1

File: inputs.0.npy
Shape: (200, 2653)
Data type: float32
Min value: 0.0
Max value: 0.24331887066364288
Mean value: 0.0007819356396794319
Last value: 0.015599999576807022

First few elements:
[0.00467351 0.00847105 0.00034537 0.00055354 0.00339675 0.00150516
 0.00181851 0.00088251 0.00024867 0.00062379]

File: targets.0.npy
Shape: (200, 2652)
Data type: float32
Min value: -1.1727287769317627
Max value: 59.63296127319336
Mean value: 0.3144921064376831

First few elements:
[-0.5962468  -0.5926242  -0.5474061  -0.5954425  -0.59046686 -0.586307

In [7]:
filepath =  "models/PyStack/data/TrainSamples/river/root_nodes_npy/boards.0.npy"
import numpy as np
import sys
import os

def visualize_npy(file_path):
    # Load the numpy array
    data = np.load(file_path)
    
    # Print basic information
    print(f"\nFile: {os.path.basename(file_path)}")
    print(f"Shape: {data.shape}")
    print(f"Data type: {data.dtype}")
    print(f"Min value: {np.min(data)}")
    print(f"Max value: {np.max(data)}")
    print(f"Mean value: {np.mean(data)}")
    if file_path == "models/PyStack/data/TrainSamples/river/root_nodes_npy/inputs.0.npy":
        print(f"Last value: {data[0,-1]}")

    # Print first few elements
    print("\nFirst few elements:")
    print(data.flatten()[:10])  # Show first 10 elements
    
    # Print unique values and their counts if the array is small enough
    if data.size < 1000:  # Only for reasonably sized arrays
        unique_vals = np.unique(data, return_counts=True)
        print("\nUnique values and their counts:")
        for val, count in zip(*unique_vals):
            print(f"{val}: {count}")

def main(file_path):
    if not os.path.exists(file_path):
        print(f"File not found: {file_path}")
        return
        
    visualize_npy(file_path)

print(filepath)

for filepath in ["models/PyStack/data/TrainSamples/river/root_nodes_npy/boards.0.npy", "models/PyStack/data/TrainSamples/river/root_nodes_npy/inputs.0.npy", "models/PyStack/data/TrainSamples/river/root_nodes_npy/targets.0.npy"]:
    main(filepath)

models/PyStack/data/TrainSamples/river/root_nodes_npy/boards.0.npy

File: boards.0.npy
Shape: (2, 5)
Data type: uint8
Min value: 0
Max value: 49
Mean value: 21.5

First few elements:
[ 0  1 49 44  2 33 40  6 28 12]

Unique values and their counts:
0: 1
1: 1
2: 1
6: 1
12: 1
28: 1
33: 1
40: 1
44: 1
49: 1

File: inputs.0.npy
Shape: (200, 2653)
Data type: float32
Min value: 0.0
Max value: 0.2796363830566406
Mean value: 0.0007579344091936946
Last value: 0.016599999740719795

First few elements:
[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 6.568274e-06]

File: targets.0.npy
Shape: (200, 2652)
Data type: float32
Min value: 0.0
Max value: 0.0
Mean value: 0.0

First few elements:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
